### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by pedrothedim** [Ant2888/NMSExtender#4]
I have followed installation instructions and my game does not seem to be able to launch when double clicking NMSELauncher.exe - nor does it work through running as administrator.

Using version 1.1.0 NMSEAlphav1.1.0 from NexusMods.

PS: I'm using the experimental version that Hello Games released.

UPDATE

It works! I had to follow these steps:

> If your NMSE is constantly crashing delete everything inside your \binaries\ folder and verify your cache (either with gog or steam)
> (Taken from [here](http://www.nexusmods.com/nomanssky/mods/11/?tab=1&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fnomanssky%2Fajax%2Fmoddescription%2F%3Fid%3D11%26preview%3D&pUp=1))

Only problem is: my HUD cannot be toggled. (Pressing F5 has no effect whatsoever)

**Comment by Ant2888** [comment]
You need to make sure you're launching the game through NMSELauncher. Also make sure that there is an folder in binaries Called NMSE with your NoHUD.dll inside.

Take a picture of directory and link it to me.
