### ISSUE TITLE
unable to compile from source

### ISSUE THREAD

**Issue by jimmon89** [Ant2888/NMSExtender#7]
i've tried to compile from source in vs 2012 and 2013 express editions and 2015 community edition
2012 complains that the solution is improperly formated, except for the "NoHUD" vcproj file. which is made in 2012, and in 2013 all of the projects in the solution fail to compile, i've tried compileing all of them as is, as all of them except for "NoHUD" were written in 2013, and i've also tried upgrading "NoHUD to 2013 to no avail.
and ive also tried upgrading them all to vs 2015 with no success.
i have all 3 installed currently on windows 10.
i must be missing something, if you want a look at the compile logs for 2013 im going to upload them with this post.
[Debug.zip](https://github.com/Ant2888/NMSExtender/files/430688/Debug.zip)

**Comment by jimmon89** [comment]
the errors im getting are
error LNK1561: entry point must be defined   -NMSE_Libs
error C1083: Cannot open include file: 'NMSE_Libs\Hooking.h': No such file or directory  -NMSE_Core_1_0
error C1083: Cannot open include file: 'NMSE_Libs\Hooking.h': No such file or directory  -NMSELauncher
error C1083: Cannot open include file: 'NMSE_Libs\Hooking.h': No such file or directory  -NMSE_steam
error C1083: Cannot open include file: 'NMSE_Core_1_0\ModAPI.h': No such file or directory  -TabbingFixExample

**Comment by Ant2888** [comment]
You have messed up the vcproj files by attempting to upgrade them. The project will open fine in VS2012 or VS2013 but will require some modification for VS2014+. 

All of the projects are configured as x64 and /MTd:
Core, NoHUD, TabbingFix, and Steam are all dynamic DLL's while Libs is a static DLL and Launcher is an application.

Judging by your error it is not configured that way. I'd recommend re-downloading this GIT and trying again without upgrading (you could probably get away with upgrading to VS2013).

**Comment by jimmon89** [comment]
in between attempts to compile i redownloaded the files and started clean
every time i tried

**Comment by jimmon89** [comment]
got it,
the release configuration is not set up(properly or even at all)
when i compiled it as debug as you stated it succeeded first try
--edit--
thanks for the help, i'm a big fan of your work

**Comment by Ant2888** [comment]
Thanks, yea it shouldn't default to Release but everything is set to /MTd, Multi-Threaded debug so :)

**Comment by jimmon89** [comment]
all good, ty again :)
