### ISSUE TITLE
Incompatibility with ReShade/SweetFX

### ISSUE THREAD

**Issue by deepfriedmind** [Ant2888/NMSExtender#8]
It seems that when the ReShade/SweetFX DLL is present in the `Binaries` directory, `NMSELauncher.exe` consistently fails to launch, i.e. `NMS.exe` crashes immediately and silently, after which the CMD prompt closes.

**Comment by Ant2888** [comment]
Update everything and tell me if you are getting errors. If so link me the mods.

**Comment by deepfriedmind** [comment]
Everything is up to date on my end. It doesn't matter if I have any mods active or not - as long as `opengl32.dll` is present, the game instantly crashes upon launch while the CMD prompt lingers on for a bit and then disappears.

**Comment by Ant2888** [comment]
Fixed by moving the load order of the opengl32.dll
